services:
 mysql:
  image: mysql:8.0
  container_name: mysql-db
  environment:
   MYSQL_ROOT_PASSWORD: root123
   MYSQL_DATABASE: login_db
   MYSQL_USER: vittal777
   MYSQL_PASSWORD: 696969
 
  volumes:
   - mysql-data:/var/lib/mysql
  healthcheck:
   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
   interval: 5s
   timeout: 5s
   retries: 20
 springboot:
  build: .
  container_name: login-app
  ports:
   - "1725:1725"
  depends_on:
   mysql:
    condition: service_healthy 
volumes:
 mysql-data: