pipeline {
    agent {
		docker{
			image 'maven:3.9.11-eclipse-temurin-17'
		}
	}

    stages {

        stage('Build') {
            steps {
				dir('LoginPage'){
                sh 'mvn --version'
                sh 'mvn clean package -DskipTests'
                }
            }
        }
    }
}