pipeline {
    agent {
		docker{
			image 'maven-docker-agent'
			args '''
			-u root 
			-v /var/run/docker.sock:/var/run/docker.sock
			-v /home/vittalc/.kube:/root/.kube
        	-v /home/vittalc/.minikube:/root/.minikube
        	-e KUBECONFIG=/root/.kube/config
			'''
		}
	}

    stages {

        stage('Build') {
            steps {
				dir('LoginPage'){
                sh 'mvn --version'
                sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Docker Image Build'){
			steps{
				sh 'docker build -t loginpage-springboot:${BUILD_NUMBER} LoginPage'
			}
		}
		stage('Push Docker Image'){
			steps{
				withCredentials([usernamePassword(
					credentialsId: 'docker_hub-credentials',
					usernameVariable: 'DOCKER_USER',
					passwordVariable: 'DOCKER_PASS'
				)]){
					
					sh '''
					echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
					
					docker tag loginpage-springboot:${BUILD_NUMBER} $DOCKER_USER/loginpage-springboot:${BUILD_NUMBER}
					docker tag loginpage-springboot:${BUILD_NUMBER} $DOCKER_USER/loginpage-springboot:latest
					
					docker push $DOCKER_USER/loginpage-springboot:${BUILD_NUMBER}
					docker push $DOCKER_USER/loginpage-springboot:latest
					
					docker logout
					'''
				}
			}
		}
		stage('Check Kubernetes'){
			steps{
				sh '''
				echo "KUBECONFIG=$KUBECONFIG"
				
				ls -la /root/.kube
        		ls -la /root/.minikube
        		cat /root/.kube/config
				kube config view
				kubectl config current-context
				kubectl get nodes
				helm version
				'''
			}
		}
		stage('Deploy to Kubernetes'){
			steps{
				sh '''
				 helm upgrade --install login-app ./login-chart
				 '''
			}
		}
    }
    post{
		success{
			archiveArtifacts artifacts: 'LoginPage/target/*-SNAPSHOT.jar', fingerprint: true
			echo 'Application deployed successfully'
		}
		failure{
			echo 'Pipeline failed.'
		}
	}
}