pipeline {
    agent {
		docker{
			image 'maven-docker-agent'
			args '''
			--network minikube
			-u root 
			-v /var/run/docker.sock:/var/run/docker.sock
			'''
		}
	}

    stages {

        stage('Build') {
            steps {
				dir('LoginPage'){
                sh 'mvn --version'
                sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Docker Image Build'){
			steps{
				sh 'docker build -t loginpage-springboot:${BUILD_NUMBER} LoginPage'
			}
		}
		stage('Pushing Docker Image'){
			steps{
				withCredentials([usernamePassword(
					credentialsId: 'docker_hub-credentials',
					usernameVariable: 'DOCKER_USER',
					passwordVariable: 'DOCKER_PASS'
				)]){
					
					sh '''
					echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
					
					docker tag loginpage-springboot:${BUILD_NUMBER} $DOCKER_USER/loginpage-springboot:${BUILD_NUMBER}
					docker tag loginpage-springboot:${BUILD_NUMBER} $DOCKER_USER/loginpage-springboot:latest
					
					docker push $DOCKER_USER/loginpage-springboot:${BUILD_NUMBER}
					docker push $DOCKER_USER/loginpage-springboot:latest
					
					docker logout
					'''
				}
			}
		}
		stage('Update GitOps Repo') {
    steps {
        dir('loginpage-gitops') {
            git branch: 'main',
                credentialsId: 'gitops-repo',
                url: 'https://github.com/Vittal777/loginpage-gitpos.git'

            sh '''
                sed -i "s/tag: \".*\"/tag: \"${BUILD_NUMBER}\"/" login-chart/values.yaml

                git config user.name "Jenkins"
                git config user.email "jenkins@localhost"

                git add login-chart/values.yaml
                git commit -m "Update image tag to ${BUILD_NUMBER}" || true
                git push origin main
            '''
        }
    }
}

    }
    post{
		success{
			archiveArtifacts artifacts: 'LoginPage/target/*-SNAPSHOT.jar', fingerprint: true
			echo 'Application deployed successfully'
		}
		failure{
			echo 'Pipeline failed.'
		}
	}
}