spring.application.name=LoginPage
server.port =1725

spring.datasource.url =jdbc:mysql://mysql:3306/login_db
spring.datasource.username =vittal777
spring.datasource.password =696969


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect